services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bacona
    ports:
      - "5432:5432"
    volumes:
      - bacona_pgdata:/var/lib/postgresql/data

volumes:
  bacona_pgdata:

